### ISSUE TITLE
github-action-merge-dependabot: how to wait automerge until all github-actions checks have passed

### ISSUE THREAD

**Issue by Clumsy-Coder** [fastify/help#741]
## 💬  Question here 

I'm using [github-action-merge-dependabot](https://github.com/fastify/github-action-merge-dependabot) to automerge dependabot Pull requests.

How do I make it wait automerging until all Github-action checks have passed.

From what I observed, github would create a pull request to update the npm package (in this example), the github-action **github-action-merge-dependabot** will run it's workflow and automerge the pull request before any of the github-action checks from (other workflows) have passed

Is there a way to make dependabot automerge github action ONLY automerge AFTER all the other github-action checks have passed?

### `.github/workflows/dependabot-automerge.yml`

```yaml
name: Dependabot automerge
on: [push, pull_request]
# description: Automerge dependabot pull requests

jobs:
  automerge-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: |
      startsWith(github.event.pull_request.title, 'build(deps):') ||
      startsWith(github.event.pull_request.title, 'build(devDep):')
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

```

### `.github/dependabot.yml`

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'build(deps): '
      prefix-development: 'build(devDep): '

```

## Your Environment

- *node version*: 10, 12, 13
- *os*: Linux, ubuntu-latest
- using `github-action`
