### ISSUE TITLE
Empty Response

### ISSUE THREAD

**Issue by msrumon** [fastify/help#766]
#### You have already researched for similar issues?

I tried, but couldn't find any.

#### What are you trying to achieve, or the steps to reproduce?

I'm trying to make my fastify app to work. I've pulled the example code from the **Getting Started** page on the website, but I can't get any response when I send requests to it. Also there's no error logs in the console. The project setup and reproduction steps are as follows:

#### Setup

Create `docker-compose.yml` file and paste the following in there:

```yaml
services:
  app:
    image: node:lts-alpine
    working_dir: /tmp/app
    volumes:
      - .:/tmp/app
    environment:
      PORT: 1234
    ports:
      - 80:1234
    command:
      - npm
      - run
      - dev
  npm:
    image: node:lts-alpine
    working_dir: /tmp/app
    volumes:
      - .:/tmp/app
    entrypoint:
      - npm
```

Create `package.json` file and paste the following in there:

```json
{
  "name": "app",
  "version": "0.0.0",
  "scripts": {
    "dev": "nodemon --legacy-watch server.mjs"
  },
  "private": true,
  "dependencies": {
    "fastify": "^4.7.0"
  },
  "devDependencies": {
    "nodemon": "^2.0.20"
  }
}
```

Create `server.mjs` file and paste the following in there:

```javascript
import Fastify from 'fastify';

const fastify = Fastify({ logger: true });

fastify.get('/', async (_request, _reply) => {
  return { hello: 'world' };
});

const { PORT: port } = process.env;

try {
  await fastify.listen({ port });
} catch (error) {
  fastify.log.error(error);
  process.exit();
}
```

#### Steps

1. Run `docker compose run --rm npm i`.
2. Run `docker compose up -d app`.
3. Wait for the server to be spun up. Visit <http://localhost> on your browser thereafter.

> I could've provided with a repo, but it's not too difficult to set it up by yourself (only 3 files to create). So here you go.

#### What was the result you received?

In the browser, I got `ERR_EMPTY_RESPONSE` error.

#### What did you expect?

I wanted to see the response sent by the app.

#### Context

- *node version*: 16.17.1
- *fastify version*: 4.7.0
- *os*: Windows 10 Pro
